receivers:
  hostmetrics:
    root_path: /hostfs
    collection_interval: 1s
    scrapers:
      cpu:
      memory:
      load:
      filesystem:
      disk:
      network:
      paging:
      process:

processors:
  resourcedetection:
    detectors: [system]
    timeout: 2s
    override: false
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  influxdb:
    endpoint: http://influxdb:8086
    timeout: 5s
    org: llm
    bucket: llm
    token: llm_admin_token_change_me
    metrics_schema: telegraf-prometheus-v2

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [influxdb]
